services:
  backend:
    image: oholala/optimas-backend:small
    container_name: optimas-backend
    volumes:
      - ${DATA_PATH}:/app/data
    ports:
      - "8000:8000"

  optimas:
    image: oholala/optimas-frontend:latest
    container_name: optimas-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

